### ISSUE TITLE
Measurement parameters not always used in list mode (not sure if this is an issue)

### ISSUE THREAD

**Issue by davidbrought** [hnordquist/INCC6#135] opened 2016-12-06 22:35 UTC
Testing 6.18.32 in list mode some more.. 

If the detector you are using is set-up to have fast accidentals (selected under measurement parameters) the other detector specific measurement parameters are only used when the analysis method is "Fast Multiplicity", if "Multiplicity" is used they are not used. The opposite is true for having fast accidentals off where "Multiplicity" needs to be used to use the detector specific parameters. 

Is there a difference between multiplicity and fast multiplicity analysis? If there isn't would it be possible to combine them and always use the detector parameters? (unless the gate width and predelay are specifically changed in the Analysis Params)

**Comment by davidbrought** [comment] 2016-12-06 23:44
Also, sometimes when you select "Acquire | Rates Only" the list mode measurement starts without asking you what list mode analysis method to use. For me it happens when fast accidentals are on.

**Comment by ghost** [comment] 2016-12-07 08:16
OK, it might be flaky.
This was intended:

> If a virtual SR is defined and active it will just go ahead and do the measurement. The LM Acquire dlg is shown only if some configuration is required to prepare an active virtual SR.

BTW the Pu analysis methods are only used for Calibration and Verification measurements.

**Comment by ghost** [comment] 2016-12-07 08:19
Yes there is a big difference between FA and not,  triggered "fast", and conventional. Plenty of discussion in the literature and the report Jonathan Dowell and I prepared on the list mode analsyis details. I forget the LA-CP number, look it up in the library, it is from 2011 I think

**Comment by hnordquist** [comment] 2016-12-07 14:27
I think I have Jonathan's report in my inbox somewhere. Remind me, David
and I will get it to you.

Heather

**Comment by davidbrought** [comment] 2016-12-07 19:03
The output from ptr list mode "Acquire | Rates Only" seems to be different depending on the detector settings. Talking with Heather it seems to make sense to output either the conventional or fast accidentals analysis based on what is selected under "Measurement Parameters".

Using the default Measurement Parameters with fast accidentals ON the output .rts file is a fast accidentals rate analysis. The log for that is: [LOG1.txt](https://github.com/hnordquist/INCC6/files/637440/LOG1.txt)

Using the default Measurement Parameters with fast accidentals OFF the output is two .rts files, so you get both fast accidentals and a conventional rate analysis. The log for that is: [LOG2.txt](https://github.com/hnordquist/INCC6/files/637446/LOG2.txt)

Then trying the same thing with Measurement Parameters changed from the default values with fast accidentals ON the output is two .rts files, so you get both fast accidentals and a conventional rate analysis. The log for that is: [LOG3.txt](https://github.com/hnordquist/INCC6/files/637462/LOG3.txt)

Again with Measurement Parameters changed from the default values with fast accidentals OFF it doesn't start a rates measurement, this window pops up (this is the same as if you had selected "Acquire | List Mode"): ![lm](https://cloud.githubusercontent.com/assets/24234147/20982179/a2bc6694-bc74-11e6-95ae-968883923bee.jpg)
The log for that is: [LOG4.txt](https://github.com/hnordquist/INCC6/files/637477/LOG4.txt)

(all of the cases except for 4 where the measurement wasn't run also produce the .csv file that corresponds to the .rts files generated, as well as the .bin and .chn files)

**Comment by davidbrought** [comment] 2016-12-07 23:20
This is also related to using "Acquire | Rates Only", but for reanalysis from the PTR-32 data file pair. 

During the reanalysis the detector parameters that are used depend on how you take the measurement.

I was able to change the gate width and preserve the other parameters like efficiency and deadtime by following these steps (this is the same with fast accidentals on or off):
Select "Acquire | Rates Only", with PTR-32 data file pair as the data source hit ok.
Go to the File Settings tab. Select the files to re-analyze and Save Changes. 
Go to Analysis Params and select Save Changes (you need to use the gate width that is already set on the Analysis Params page, if you change the gate width at this step all of the detector parameters revert to the default values. The way to get around this is to save the gate width that you want to analyze, close the window and then follow these steps).
This is the log: [Log-reanalysis.txt](https://github.com/hnordquist/INCC6/files/637976/Log-reanalysis2.txt)

**Comment by hnordquist** [comment] 2016-12-08 00:07
Joe, I got stuck doing other stuff. I think I have merged your branches into the master. If you have time to look at this, would be great. I will work with David on it in the morning.

**Comment by ghost** [comment] 2016-12-08 08:20
Ok, I will get into later today.

**Comment by hnordquist** [comment] 2016-12-08 18:03
I have fixed one problem, but now have to figure out another.

**Comment by davidbrought** [comment] 2016-12-08 21:53
Talking about this with Martyn it makes sense to have all of the Acquire modes other than "Acquire | List Mode" function as close as possible to a JSR. 

Instead of the way it is now with the "List mode data collection and analysis" window sometimes popping up directly use the settings for gate width and conventional/fast accidentals from the "Measurement Parameters" for all of these types of analysis (rates, background, verification...). 

This should avoid the confusion I had yesterday where I had different types of rates analysis happening for different settings. 

Does that seem like it would work? The only time where the "List mode data collection and analysis" window seems unavoidable is when the data source is a ptr-32 data file pair. When analyzing a data file pair the gate widths from the "Measurement Parameters" should get set as the value for the multiplicity or fast multiplicity analysis (right now a change under "Measurement Parameters" doesn't get carried over to the "List mode data collection and analysis" window, but a "List mode data collection and analysis" gate change is carried over to the "Measurement Parameters").

**Comment by ghost** [comment] 2016-12-09 06:54
Ok the current behavior is a first try, so I can make the modifications suggested. The basic concept is the measurement parameters are used to create a new multiplicity analyzer and then you are presented with the LM option tabs, so that you may examine and change the three parameters.
Predefining a multiplicity analyzer should cause the acquire ops to automatically pick it and proceed

Sent from my iPhone

**Comment by ghost** [comment] 2016-12-09 08:36
> close as possible to a JSR.
Which kind of JSR?

**Comment by ghost** [comment] 2016-12-09 13:37
Basic Acquire behavior with LM:  Again with less typos
[Uploading LM note.docx…]()

**Comment by hnordquist** [comment] 2016-12-09 13:40
Joe, it is confusing and so we plan to put together a requirements doc
(description) of how this should look. I have done what needed doing for
the demo next week. Are you in from now until Christmas?

**Comment by ghost** [comment] 2016-12-09 13:45
Yes I am here until Dec. 20, back Jan 9. I read emails anyway. Please read the doc I just added to this issue. It shows the essential behavior that Dave Beddingfield and others specified for the INCC5 analysis from an LM device. I should prep those original requirements, but you're going to change them so it doesn't matter now.

**Comment by hnordquist** [comment] 2016-12-09 13:51
Will do for comparison. We are busy w/Japanese visitors next week, but I'll
try to get to you before the holiday.

**Comment by ghost** [comment] 2016-12-09 13:52
OK cool

This email message is intended only for the use of the named recipient. Information contained in this email message and its attachments may be privileged, confidential and protected from disclosure. If you are not the intended recipient, please do not read, copy, use or disclose this communication to others. Also please notify the sender by replying to this message and then delete it from your system.

**Comment by davidbrought** [comment] 2016-12-09 15:45
It's a JSR-15. The idea was just to make it possible for sometime who normally uses a shift register to take a list mode measurement in the same way.

**Comment by davidbrought** [comment] 2016-12-13 22:01
Back to the earlier Fast Multiplicity vs. Multiplicity comparison.. It makes sense that this is for setting the shift register mode, but I think it might be clearer to label them "Multiplicity (Fast Accidentals)" and "Multiplicity" or "Multiplicity (conventional)". Fast multiplicity sounds like it could be something different than fast accidentals.

**Comment by ghost** [comment] 2016-12-16 11:17
Ok I made the change to "Multiplicity (Fast Accidentals)"

**Closed as completed** 2018-07-02 15:26 UTC
Labels: List Mode
